version: "3.8"
services:
  client-app:
    image: client-app-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "80:80"
      - "443:443"
    networks:
      - blogsite
  api-server:
    image: api-server
    restart: unless-stopped
    env_file: ./BlogSite-API/env/.env.${ENV}
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    networks:
      - blogsite
networks:
  blogsite:
    driver: bridge