version: "3.8"
services:
  client-app:
    image: client-app
    build: ./client/
    stdin_open: true
    ports:
      - $REACT_LOCAL_PORT:$REACT_LOCAL_PORT
    networks:
      - blogsite
  api-server:
    image: api-server
    build: ./server/
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    networks:
      - blogsite
networks:
  blogsite:
    driver: bridge