version: 2.1
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker image
          command: |
            make build-for-prod
workflows:
  build-test-deploy:
    jobs:
      - build-and-test